/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as M3RouteImport } from './routes/m3'
import { Route as M2RouteImport } from './routes/m2'
import { Route as M1RouteImport } from './routes/m1'
import { Route as FutureModulesRouteImport } from './routes/future-modules'
import { Route as DataRouteImport } from './routes/data'
import { Route as IndexRouteImport } from './routes/index'

const M3Route = M3RouteImport.update({
  id: '/m3',
  path: '/m3',
  getParentRoute: () => rootRouteImport,
} as any)
const M2Route = M2RouteImport.update({
  id: '/m2',
  path: '/m2',
  getParentRoute: () => rootRouteImport,
} as any)
const M1Route = M1RouteImport.update({
  id: '/m1',
  path: '/m1',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureModulesRoute = FutureModulesRouteImport.update({
  id: '/future-modules',
  path: '/future-modules',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/future-modules': typeof FutureModulesRoute
  '/m1': typeof M1Route
  '/m2': typeof M2Route
  '/m3': typeof M3Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/future-modules': typeof FutureModulesRoute
  '/m1': typeof M1Route
  '/m2': typeof M2Route
  '/m3': typeof M3Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/future-modules': typeof FutureModulesRoute
  '/m1': typeof M1Route
  '/m2': typeof M2Route
  '/m3': typeof M3Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/data' | '/future-modules' | '/m1' | '/m2' | '/m3'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/data' | '/future-modules' | '/m1' | '/m2' | '/m3'
  id: '__root__' | '/' | '/data' | '/future-modules' | '/m1' | '/m2' | '/m3'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataRoute: typeof DataRoute
  FutureModulesRoute: typeof FutureModulesRoute
  M1Route: typeof M1Route
  M2Route: typeof M2Route
  M3Route: typeof M3Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/m3': {
      id: '/m3'
      path: '/m3'
      fullPath: '/m3'
      preLoaderRoute: typeof M3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m2': {
      id: '/m2'
      path: '/m2'
      fullPath: '/m2'
      preLoaderRoute: typeof M2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m1': {
      id: '/m1'
      path: '/m1'
      fullPath: '/m1'
      preLoaderRoute: typeof M1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future-modules': {
      id: '/future-modules'
      path: '/future-modules'
      fullPath: '/future-modules'
      preLoaderRoute: typeof FutureModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataRoute: DataRoute,
  FutureModulesRoute: FutureModulesRoute,
  M1Route: M1Route,
  M2Route: M2Route,
  M3Route: M3Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
